### ISSUE TITLE
what's the algo behind this program?

### ISSUE THREAD

**Issue by ruinmi** [PythonGermany/amongUsFinder#1]

**Comment by PythonGermany** [comment]
I created my own algorithm using my own ides with the additional goal to make it run as fast as I can on the CPU by using multithreading. However now, when I look back on the code the code itself looks bad and is very hard to improve upon, I've gotten much better at writing structured and maintainable code since then. If you want detailed explanation of my approach I can explain to you, if you want just say it.

**Comment by ruinmi** [comment]
Your program impresses me. I can't figure out how to find the amongus shape. Did you use opencv? I would appreciate it if you could explain it.

**Comment by ruinmi** [comment]
And finding amongus in the r/place image is a very interesting idea!

**Comment by PythonGermany** [comment]
Ok, so in the file [SearchAmongUs.cs](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs) is a variable that defines the possible shapes of the amongus called [amongus](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L26-L30). This array defines different possible shapes of an amongus by assigning different numbers for different parts of the shape, e.g '1' for the eyes, '2' for required matching pixel and '3' for optional matching pixel. To understand the actual search process it is only important to understand the function [searchShape](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L253) , once you understood this function you will know how I search for an among us at one individual pixel in an image and I basically call this function for each pixel in an image (just very complicated and confusing because I multithread the search of one image by splitting it into 4 parts and on top of that if there are enough threads available I mutlithread to process multiple images in parallel. Thats the reason why much of it is so unstructured, I didn't know how to code it better a year ago). So now to explain the [searchShape](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L253) function: [this ](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L255-L264) part compares the colors of the [amongus](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L26-L30) array with the colors at the image locating the function is called on, if the [color comparison](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L260) is not a match and the pixel is required to be a match I return from the function and don't highlight the location in the output image. If everything in the matching part is a match I continue on [checking the bordering pixels](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L265-L273) of the shape, I keep track of how many bordering pixel match using the variable 'border'. If there are to may bordering pixel with the same color as the amongus I skip the next part of the function, however if there are enough different bordering pixel I [continue to highlight the shape on the final image](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L275-L290). If you have any further question feel free to ask :-)

**Comment by ruinmi** [comment]
> Ok, so in the file [SearchAmongUs.cs](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs) is a variable that defines the possible shapes of the amongus called [amongus](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L26-L30). This array defines different possible shapes of an amongus by assigning different numbers for different parts of the shape, e.g '1' for the eyes, '2' for required matching pixel and '3' for optional matching pixel. To understand the actual search process it is only important to understand the function [searchShape](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L253) , once you understood this function you will know how I search for an among us at one individual pixel in an image and I basically call this function for each pixel in an image (just very complicated and confusing because I multithread the search of one image by splitting it into 4 parts and on top of that if there are enough threads available I mutlithread to process multiple images in parallel. Thats the reason why much of it is so unstructured, I didn't know how to code it better a year ago). So now to explain the [searchShape](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L253) function: [this ](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L255-L264) part compares the colors of the [amongus](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L26-L30) array with the colors at the image locating the function is called on, if the [color comparison](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L260) is not a match and the pixel is required to be a match I return from the function and don't highlight the location in the output image. If everything in the matching part is a match I continue on [checking the bordering pixels](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L265-L273) of the shape, I keep track of how many bordering pixel match using the variable 'border'. If there are to may bordering pixel with the same color as the amongus I skip the next part of the function, however if there are enough different bordering pixel I [continue to highlight the shape on the final image](https://github.com/PythonGermany/amongUsFinder/blob/main/amongUsFinder/SearchAmongus.cs#L275-L290). If you have any further question feel free to ask :-)

that's brilliant! genius.. Did you do any algo pratice related to this project before?
sorry for late reply:-(

**Comment by PythonGermany** [comment]
No, I had little to no general programming experience before doing this project.
